# Generated by Django 4.1.3 on 2023-05-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number1', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('phone_number2', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'News'), (2, 'Finish'), (3, 'Delete')], default=1)),
                ('free_time', models.CharField(max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.science')),
            ],
        ),
    ]
